### ISSUE TITLE
Add MVP authentication and authorization

### ISSUE THREAD

**Issue by rightfold** [channable/icepeak#9]
The current situation is that requests must include a token which is set when starting Icepeak. It is not possible to customize which users may touch what data.

We will implement support for authorization by switching to [JWT][jwt]. The JWT token will include a claim called `"icepeak"` that has the following JSON schema:

```json
{
  "type": "object",
  "required": ["version"],
  "properties": {
    "version": {"enum": [1]},
    "whitelist": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["prefix", "modes"],
        "properties": {
          "prefix": {"type": "array", "items": {"type": "string"}},
          "modes": {"type": "array", "items": {"enum": ["read", "write"]}}
        }
      }
    }
  }
}
```

Example JWT token claim set:

```json
{
  "icepeak": {
    "version": 1,
    "whitelist": [
      {"prefix": ["foo"], "modes": ["read"]},
      {"prefix": ["bar", "1"], "modes": ["read", "write"]}
    ]
  }
}
```

A request with this claim set may only:
 - Read paths that have `/foo` as a prefix.
 - Update paths that have `/bar/1` as a prefix.
Any other request will result in a *401 Unauthorized* response.

A token can be specified in an `Authorization: Bearer <token>` header or an `access_token=<token>` query string parameter.

Requests that do not include a token will always be responded to with a *401 Unauthorized* error.

[jwt]: https://tools.ietf.org/html/rfc7519

**Comment by fatho** [comment]
Should we also differentiate between read and write access?

**Comment by rightfold** [comment]
Good point. I will add that to the schema.

**Comment by rkrzr** [comment]
> Should we also differentiate between read and write access?

Yes, but let's support all of create, read, update and delete.

**Comment by rightfold** [comment]
Added those to the schema.

**Comment by fatho** [comment]
We need to decide on a semantics for whitelisting, in particular when there are multiple entries that apply to the same path, as in the following example. (@rkrzr: regarding our discussion yesterday)

Suppose we have the following whitelist

```
{"prefix": ["foo"], "modes": ["read"]},
{"prefix": ["foo"], "modes": ["update"]}
```

Then I'd say that this is valid and would allow both `read` and `update` actions on all paths prefixed by `/foo/`, because for all such actions there is an entry that allows it.

Similarly, the whitelist

```
{"prefix": ["foo"], "modes": ["update"]},
{"prefix": ["foo", "bar"], "modes": ["read"]}
```

would also allow updating `/foo/bar` because that is allowed by the first entry.

That interpretation makes whitelists easy to reason about, i.e. "access granted whenever there's an entry that allows it" and no complex validation logic is needed.

If at some point we would like to restrict permissions of sub-paths of whitelisted paths, we could always introduce an additional blacklist, that can be used to selectively withdraw permissions from previously whitelisted paths.

**Comment by rightfold** [comment]
Yes, I think taking the union of all the whitelist entries is the most sensible policy.

Restricting privileges in subpaths is tricky, because then you can't just replace the parent JSON object by a new one. Certain competitor JSON document stores with push notifications also do not support this use case.

**Comment by rkrzr** [comment]
> Yes, I think taking the union of all the whitelist entries is the most sensible policy.

Agreed. Let's keep it simple.

**Comment by fatho** [comment]
For the sake of simplicity, we start out with just `read` and `write` permissions. I've edited the issue description accordingly.
